import type { App } from 'vue';
import {
  NAlert,
  NButton,
  NCard,
  NCheckbox,
  NCheckboxGroup,
  NCode,
  NConfigProvider,
  NDataTable,
  NDialogProvider,
  NDivider,
  NForm,
  NFormItem,
  NGi,
  NGlobalStyle,
  NGrid,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NLoadingBarProvider,
  NMenu,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPopconfirm,
  NRadio,
  NRadioGroup,
  NSelect,
  NSpin,
  NSpace,
  NSwitch,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NTreeSelect,
} from 'naive-ui';

// Important: Naive UI component `.name` is like "Button"/"MessageProvider",
// but we use `<n-button>`/`<n-message-provider>` in templates, which resolves
// to registered name `NButton`/`NMessageProvider`. So we must register by the
// imported identifier name (prefixed with `N`), not by `.name`.
const namedComponents: Record<string, any> = {
  NConfigProvider,
  NGlobalStyle,
  NLoadingBarProvider,
  NDialogProvider,
  NNotificationProvider,
  NMessageProvider,
  NSpin,
  NLayout,
  NLayoutSider,
  NLayoutHeader,
  NLayoutContent,
  NMenu,
  NSpace,
  NText,
  NCard,
  NButton,
  NForm,
  NFormItem,
  NInput,
  NInputNumber,
  NSelect,
  NSwitch,
  NRadioGroup,
  NRadio,
  NTabs,
  NTabPane,
  NDivider,
  NDataTable,
  NModal,
  NPopconfirm,
  NTag,
  NCode,
  NTreeSelect,
  NGrid,
  NGi,
  NAlert,
  NCheckboxGroup,
  NCheckbox,
};

export function setupNaive(app: App) {
  for (const [name, component] of Object.entries(namedComponents)) {
    app.component(name, component);
  }
}
