import type { App } from 'vue';
import {
  NAlert,
  NButton,
  NCard,
  NCheckbox,
  NCheckboxGroup,
  NCode,
  NConfigProvider,
  NDataTable,
  NDialogProvider,
  NDivider,
  NForm,
  NFormItem,
  NGi,
  NGlobalStyle,
  NGrid,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NLoadingBarProvider,
  NMenu,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPopconfirm,
  NRadio,
  NRadioGroup,
  NSelect,
  NSpin,
  NSpace,
  NSwitch,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NTreeSelect,
} from 'naive-ui';

// 重要：Naive UI 组件 `.name` 类似于 "Button"/"MessageProvider"，
// 但我们在模板中使用 `<n-button>`/`<n-message-provider>`，它解析为
// 注册的名称 `NButton`/`NMessageProvider`。所以我们必须通过
// 导入的标识符名称（前缀为 `N`）进行注册，而不是通过 `.name`。
const namedComponents: Record<string, any> = {
  NConfigProvider,
  NGlobalStyle,
  NLoadingBarProvider,
  NDialogProvider,
  NNotificationProvider,
  NMessageProvider,
  NSpin,
  NLayout,
  NLayoutSider,
  NLayoutHeader,
  NLayoutContent,
  NMenu,
  NSpace,
  NText,
  NCard,
  NButton,
  NForm,
  NFormItem,
  NInput,
  NInputNumber,
  NSelect,
  NSwitch,
  NRadioGroup,
  NRadio,
  NTabs,
  NTabPane,
  NDivider,
  NDataTable,
  NModal,
  NPopconfirm,
  NTag,
  NCode,
  NTreeSelect,
  NGrid,
  NGi,
  NAlert,
  NCheckboxGroup,
  NCheckbox,
};

export function setupNaive(app: App) {
  for (const [name, component] of Object.entries(namedComponents)) {
    app.component(name, component);
  }
}
